#!/bin/bash
source /root/build-config.sh
source /root/build-common.sh
check_vars

if [[ -z "$1" ]]; then
	echo "Please supply version number"
	exit
else
	VERSION=$1
fi

function cleanup(){
	# Remove stale wine sockets
	rm -rf /tmp/.wine-*
}

cleanup

SOURCEDIR=/opt/wine-light/drive_c/light-capricoin/Light-Capricoin-$VERSION


cd $SOURCEDIR

$PYTHON "C:/PyInstaller/pyinstaller.py" -y "C:/light-capricoin/deterministic.spec"
cp /opt/wine-light/drive_c/light-capricoin/light-capricoin.nsi $SOURCEDIR/

echo "Running c:/light-capricoin/Light-Capricoin-$VERSION/light-capricoin.nsi for install"
xvfb-run wine c:\\"Program Files"\\NSIS\\makensis.exe -V1 c:/light-capricoin/Light-Capricoin-$VERSION/light-capricoin.nsi


cleanup
test -d /root/release-packages/Windows || mkdir -pv /root/release-packages/Windows
mv /opt/wine-light/drive_c/light-capricoin/Light-Capricoin-${VERSION}/dist/light-capricoin-setup.exe /root/release-packages/Windows/Light-Capricoin-${VERSION}-Windows-setup.exe
mv /opt/wine-light/drive_c/light-capricoin/Light-Capricoin-${VERSION}/dist/light-capricoin.exe /root/release-packages/Windows/Light-Capricoin-${VERSION}-Windows.exe
